language: swift
xcode_workspace: Muslim Quiz.xcworkspace
xcode_scheme: Muslim Quiz
cache: cocoapods
osx_image: xcode10
notifications:
  email:
    - amin.benarieb@gmail.com

before_install: 
  - bundle update
before_script: 
  - openssl aes-256-cbc -K $encrypted_0c48b83b2f58_key -iv $encrypted_0c48b83b2f58_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval $(ssh-agent -s)
  - ssh-add deploy_key
  # - echo -e "Host github.com\n\tHostName github.com\n\tUser git\n\tIdentityFile ~/.ssh/deploy\n" >> ~/.ssh/config
  # - ssh-keyscan github.com >> ~/.ssh/known_hosts
  # - chmod 600 ~/.ssh/deploy
script:
  - fastlane beta --verbose
# after_success: travis/after_success_script.sh